# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_ornek_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deneme',
            field=models.BooleanField(default=False),
        ),
    ]
