# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_deneme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default=False, max_length=200),
        ),
    ]
